name: Shared Checks

on:
  workflow_call:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup UV with cache (attempt 1)
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          version: 0.7.2
        continue-on-error: true
        id: setup-uv-cache-1

      - name: Setup UV with cache (attempt 2)
        if: steps.setup-uv-cache-1.outcome == 'failure'
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          version: 0.7.2
        continue-on-error: true
        id: setup-uv-cache-2

      - name: Setup UV without cache (fallback)
        if: steps.setup-uv-cache-1.outcome == 'failure' && steps.setup-uv-cache-2.outcome == 'failure'
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: false
          version: 0.7.2

      - name: Log cache status
        run: |
          echo "UV setup with cache attempt 1: ${{ steps.setup-uv-cache-1.outcome }}"
          echo "UV setup with cache attempt 2: ${{ steps.setup-uv-cache-2.outcome }}"
          if [[ "${{ steps.setup-uv-cache-1.outcome }}" == "failure" && "${{ steps.setup-uv-cache-2.outcome }}" == "failure" ]]; then
            echo "⚠️ Cache restoration failed after 2 attempts, continuing without cache"
          else
            echo "✅ UV setup with cache successful"
          fi

      - name: Install dependencies
        run: uv sync --frozen --all-extras --python 3.10

      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files --verbose
        env:
          SKIP: no-commit-to-branch

  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup UV with cache (attempt 1)
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          version: 0.7.2
        continue-on-error: true
        id: setup-uv-cache-1

      - name: Setup UV with cache (attempt 2)
        if: steps.setup-uv-cache-1.outcome == 'failure'
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          version: 0.7.2
        continue-on-error: true
        id: setup-uv-cache-2

      - name: Setup UV without cache (fallback)
        if: steps.setup-uv-cache-1.outcome == 'failure' && steps.setup-uv-cache-2.outcome == 'failure'
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: false
          version: 0.7.2

      - name: Log cache status
        run: |
          echo "UV setup with cache attempt 1: ${{ steps.setup-uv-cache-1.outcome }}"
          echo "UV setup with cache attempt 2: ${{ steps.setup-uv-cache-2.outcome }}"
          if [[ "${{ steps.setup-uv-cache-1.outcome }}" == "failure" && "${{ steps.setup-uv-cache-2.outcome }}" == "failure" ]]; then
            echo "⚠️ Cache restoration failed after 2 attempts, continuing without cache"
          else
            echo "✅ UV setup with cache successful"
          fi

      - name: Install the project
        run: uv sync --frozen --all-extras --python ${{ matrix.python-version }}

      - name: Run pytest
        run: uv run --frozen --no-sync pytest
    continue-on-error: true
